"""Data models for pair distribution function diagnostics."""

from __future__ import annotations

import math
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import numpy as np


@dataclass(slots=True)
class PDFSeries:
    """Observed and optional calculated pair distribution function data."""

    name: str
    r: np.ndarray
    observed: np.ndarray
    calculated: np.ndarray | None = None
    sigma: np.ndarray | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    qmax: float | None = None
    source: str | None = None


@dataclass(slots=True, frozen=True)
class AnalysisConfig:
    """Configuration for deterministic PDF diagnostics."""

    max_peaks: int = 12
    smoothing_width: float = 0.05
    min_peak_distance: float = 0.15
    prominence_sigma: float = 3.0
    prominence_fraction: float = 0.05
    segment_count: int = 5
    residual_outlier_z: float = 4.0
    sampling_cv_warning: float = 0.02
    gap_ratio_warning: float = 1.5
    residual_correlation_warning: float = 0.5
    residual_bias_fraction_warning: float = 0.25


@dataclass(slots=True, frozen=True)
class Peak:
    """Detected positive peak or negative trough in G(r)."""

    position: float
    amplitude: float
    prominence: float
    width: float | None
    sign: str
    index: int


@dataclass(slots=True, frozen=True)
class ResidualSegment:
    """Residual statistics over one r interval."""

    r_start: float
    r_end: float
    count: int
    rmse: float
    mae: float
    mean: float


@dataclass(slots=True, frozen=True)
class ResidualMetrics:
    """Global diagnostics for observed-minus-calculated residuals."""

    count: int
    rmse: float
    mae: float
    mean: float
    max_abs: float
    rw: float | None
    weighted_rw: float | None
    range_normalized_rmse: float | None
    lag1_correlation: float | None
    durbin_watson: float | None
    outlier_count: int
    worst_segment_index: int | None


@dataclass(slots=True, frozen=True)
class DiagnosticFlag:
    """Machine-readable warning generated by the analysis."""

    code: str
    severity: str
    message: str


@dataclass(slots=True)
class PDFAnalysis:
    """Complete deterministic analysis result for one PDF series."""

    name: str
    source: str | None
    points_original: int
    points_used: int
    rows_removed: int
    duplicate_points_merged: int
    calculated_rows_used: int | None
    r_min: float
    r_max: float
    spacing_median: float
    spacing_min: float
    spacing_max: float
    spacing_cv: float
    gap_count: int
    nyquist_interval: float | None
    sampling_to_nyquist_ratio: float | None
    observed_min: float
    observed_max: float
    observed_mean: float
    observed_std: float
    observed_rms: float
    difference_noise_estimate: float
    amplitude_to_noise: float | None
    peaks: list[Peak]
    residual: ResidualMetrics | None
    residual_segments: list[ResidualSegment]
    flags: list[DiagnosticFlag]
    metadata: dict[str, Any]
    config: AnalysisConfig

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable representation."""

        return _to_builtin(asdict(self))


def _to_builtin(value: Any) -> Any:
    """Recursively convert scientific Python values to JSON-safe built-ins."""

    if isinstance(value, dict):
        return {str(key): _to_builtin(item) for key, item in value.items()}
    if isinstance(value, (list, tuple, set, frozenset)):
        return [_to_builtin(item) for item in value]
    if isinstance(value, np.ndarray):
        return _to_builtin(value.tolist())
    if isinstance(value, np.generic):
        return _to_builtin(value.item())
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    if isinstance(value, float) and not math.isfinite(value):
        return None
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    return str(value)
