"""Optional diffpy.structure and diffpy.srreal PDF simulation adapter."""

from __future__ import annotations

import math
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from diffpy.pdfgui.modeling.models import SimulationResult


class SrRealUnavailableError(RuntimeError):
    """Raised when the optional SrReal simulation stack is unavailable."""


@dataclass(frozen=True, slots=True)
class SrRealSimulationConfig:
    """Parameters for periodic or Debye PDF simulation."""

    mode: str = "periodic"
    scattering_type: str = "X"
    q_min: float = 0.0
    q_max: float = 25.0
    r_min: float = 0.0
    r_max: float = 30.0
    r_step: float = 0.01
    qdamp: float = 0.0
    qbroad: float = 0.0
    scale: float = 1.0


def simulate_structure_pdf(
    structure_file: str | Path,
    output_file: str | Path,
    config: SrRealSimulationConfig | None = None,
) -> SimulationResult:
    """Calculate and atomically save a structure PDF using SrReal."""

    settings = config or SrRealSimulationConfig()
    _validate_config(settings)
    structure_path = Path(structure_file).expanduser().resolve(strict=True)
    if not structure_path.is_file():
        raise ValueError(f"structure path is not a file: {structure_path}")
    output_path = Path(output_file).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        from diffpy.srreal.pdfcalculator import DebyePDFCalculator, PDFCalculator
        from diffpy.srreal.scatteringfactortable import ScatteringFactorTable
        from diffpy.structure import load_structure
    except ImportError as error:
        raise SrRealUnavailableError(
            "diffpy.structure and diffpy.srreal are required for PDF simulation"
        ) from error

    structure = load_structure(str(structure_path))
    calculator_type = PDFCalculator if settings.mode == "periodic" else DebyePDFCalculator
    calculator = calculator_type(
        qmin=settings.q_min,
        qmax=settings.q_max,
        rmin=settings.r_min,
        rmax=settings.r_max,
        rstep=settings.r_step,
    )
    calculator.qdamp = settings.qdamp
    calculator.qbroad = settings.qbroad
    calculator.scatteringfactortable = ScatteringFactorTable.createByType(settings.scattering_type)
    r_values, g_values = calculator(structure)
    r_array = np.asarray(r_values, dtype=float)
    g_array = np.asarray(g_values, dtype=float) * settings.scale
    if r_array.ndim != 1 or g_array.ndim != 1 or r_array.size != g_array.size:
        raise RuntimeError("SrReal returned incompatible r and G(r) arrays")
    if r_array.size < 2 or not np.all(np.isfinite(r_array)) or not np.all(np.isfinite(g_array)):
        raise RuntimeError("SrReal returned insufficient or non-finite PDF values")

    header = (
        f"generated by diffpy.pdfgui; structure={structure_path.name}; mode={settings.mode}; "
        f"stype={settings.scattering_type}; qmin={settings.q_min:g}; qmax={settings.q_max:g}; "
        f"qdamp={settings.qdamp:g}; qbroad={settings.qbroad:g}; scale={settings.scale:g}\n"
        "r(A) G(r)"
    )
    temporary_name = ""
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=output_path.parent,
            prefix=output_path.name + ".",
            suffix=".tmp",
            delete=False,
        ) as stream:
            temporary_name = stream.name
            np.savetxt(stream, np.column_stack((r_array, g_array)), header=header)
        os.replace(temporary_name, output_path)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)

    return SimulationResult(
        backend_id="srreal",
        structure_file=str(structure_path),
        output_file=str(output_path),
        mode=settings.mode,
        scattering_type=settings.scattering_type,
        points=int(r_array.size),
        r_min=float(r_array[0]),
        r_max=float(r_array[-1]),
        q_min=settings.q_min,
        q_max=settings.q_max,
    )


def _validate_config(config: SrRealSimulationConfig) -> None:
    if config.mode not in {"periodic", "debye"}:
        raise ValueError("mode must be 'periodic' or 'debye'")
    if config.scattering_type not in {"X", "N", "E"}:
        raise ValueError("scattering_type must be X, N, or E")
    numeric = {
        "q_min": config.q_min,
        "q_max": config.q_max,
        "r_min": config.r_min,
        "r_max": config.r_max,
        "r_step": config.r_step,
        "qdamp": config.qdamp,
        "qbroad": config.qbroad,
        "scale": config.scale,
    }
    for name, value in numeric.items():
        if not math.isfinite(float(value)):
            raise ValueError(f"{name} must be finite")
    if config.q_min < 0 or config.q_max <= config.q_min:
        raise ValueError("q_max must be greater than non-negative q_min")
    if config.r_min < 0 or config.r_max <= config.r_min:
        raise ValueError("r_max must be greater than non-negative r_min")
    if config.r_step <= 0 or config.r_step > config.r_max - config.r_min:
        raise ValueError("r_step must be positive and smaller than the r interval")
    if config.qdamp < 0 or config.qbroad < 0:
        raise ValueError("qdamp and qbroad cannot be negative")
